/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as BibliografiaRouteImport } from './routes/bibliografia'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulasIndexRouteImport } from './routes/aulas.index'
import { Route as AulasNumeroRouteImport } from './routes/aulas.$numero'

const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliografiaRoute = BibliografiaRouteImport.update({
  id: '/bibliografia',
  path: '/bibliografia',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasIndexRoute = AulasIndexRouteImport.update({
  id: '/aulas/',
  path: '/aulas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasNumeroRoute = AulasNumeroRouteImport.update({
  id: '/aulas/$numero',
  path: '/aulas/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/bibliografia': typeof BibliografiaRoute
  '/metodologia': typeof MetodologiaRoute
  '/projetos': typeof ProjetosRoute
  '/aulas/$numero': typeof AulasNumeroRoute
  '/aulas/': typeof AulasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/bibliografia': typeof BibliografiaRoute
  '/metodologia': typeof MetodologiaRoute
  '/projetos': typeof ProjetosRoute
  '/aulas/$numero': typeof AulasNumeroRoute
  '/aulas': typeof AulasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/bibliografia': typeof BibliografiaRoute
  '/metodologia': typeof MetodologiaRoute
  '/projetos': typeof ProjetosRoute
  '/aulas/$numero': typeof AulasNumeroRoute
  '/aulas/': typeof AulasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacao'
    | '/bibliografia'
    | '/metodologia'
    | '/projetos'
    | '/aulas/$numero'
    | '/aulas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacao'
    | '/bibliografia'
    | '/metodologia'
    | '/projetos'
    | '/aulas/$numero'
    | '/aulas'
  id:
    | '__root__'
    | '/'
    | '/avaliacao'
    | '/bibliografia'
    | '/metodologia'
    | '/projetos'
    | '/aulas/$numero'
    | '/aulas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  BibliografiaRoute: typeof BibliografiaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  ProjetosRoute: typeof ProjetosRoute
  AulasNumeroRoute: typeof AulasNumeroRoute
  AulasIndexRoute: typeof AulasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliografia': {
      id: '/bibliografia'
      path: '/bibliografia'
      fullPath: '/bibliografia'
      preLoaderRoute: typeof BibliografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas/': {
      id: '/aulas/'
      path: '/aulas'
      fullPath: '/aulas/'
      preLoaderRoute: typeof AulasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas/$numero': {
      id: '/aulas/$numero'
      path: '/aulas/$numero'
      fullPath: '/aulas/$numero'
      preLoaderRoute: typeof AulasNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  BibliografiaRoute: BibliografiaRoute,
  MetodologiaRoute: MetodologiaRoute,
  ProjetosRoute: ProjetosRoute,
  AulasNumeroRoute: AulasNumeroRoute,
  AulasIndexRoute: AulasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
